param functionAppName string = 'moneyGlob-afa-641-dev'
param storageAccountName string = 'moneyGlob-as-641-dev'
param appServicePlanName string = 'moneyGlob-asplan-641-dev'
param prefixName string = 'moneyGlob'
param envName string = 'dev'
