name: Deploy Azure Resources

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables
        run: |
          echo "RESOURCE_GROUP_NAME=${{ vars.OWNER_NAME }}-${{ matrix.environment }}-rg" >> $GITHUB_ENV
          echo "PARAMETER_FILE=parameters/${{ matrix.environment }}.parameters.json" >> $GITHUB_ENV
          echo ${{vars.RESOURCE_GROUP_NAME}}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show

      - name: Deploy Bicep template
        env:
          RESOURCE_GROUP_NAME: "${{ vars.OWNER_NAME }}-${{ matrix.environment }}-rg"
        run: |
          echo "Deploying to $RESOURCE_GROUP_NAME"
          az bicep upgrade
          az group create -l westus -n $RESOURCE_GROUP_NAME
          az deployment group create --resource-group $RESOURCE_GROUP_NAME --name $RESOURCE_GROUP_NAME --template-file ./bicep/main.bicep --parameters ./bicep/main.bicepparam
          echo "Deployment complete"
