name: Deploy Azure Function App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables
        run: |
          echo "RESOURCE_GROUP_NAME=${{ vars.OWNER_NAME }}-{{ matrix.environment }}-rg" >> $GITHUB_ENV
          echo "PARAMETER_FILE=parameters/${{ matrix.environment }}.parameters.json" >> $GITHUB_ENV

      - name: Set up Azure CLI
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group create --location westeurope --resource-group ${{ vars.OWNER_NAME }}-{{ matrix.environment }}-rg
